=== UBCFormulaElectric/Consolidated-Firmware/can_bus/schemas/schema_alerts.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "warnings_id": {
            "type": "integer"
        },
        "faults_id": {
            "type": "integer"
        },
        "warnings_counts_id": {
            "type": "integer"
        },
        "faults_counts_id": {
            "type": "integer"
        },
        "warnings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "id",
                    "description"
                ]
            }
        },
        "faults": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "id",
                    "description"
                ]
            }
        }
    },
    "required": [
        "warnings_id",
        "faults_id",
        "warnings_counts_id",
        "faults_counts_id",
        "warnings",
        "faults"
    ]
}

=== UBCFormulaElectric/Consolidated-Firmware/scripts/code_generation/jsoncan/quintuna/VC/VC_alerts.json
{
  "warnings_id": 601,
  "faults_id": 602,
  "warnings_counts_id": 603,
  "faults_counts_id": 604,
  "warnings": [
    {
      "name": "DummyWarning",
      "id": 500,
      "description": "Dummy Warning"
    }
  ],
  "faults": [
    {
      "name": "DummyFault",
      "id": 600,
      "description": "Dummy Fault"
    }
  ]
}
